# Generated by Django 4.1.7 on 2023-06-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('body_type', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('is_muslim', models.CharField(max_length=3)),
                ('muslim_type', models.CharField(max_length=10)),
                ('is_converted', models.CharField(max_length=7)),
                ('convert_time', models.CharField(max_length=20)),
                ('prayers', models.CharField(max_length=30)),
                ('masjid', models.CharField(max_length=40)),
            ],
        ),
    ]
