# Generated by Django 4.1.7 on 2023-06-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='is_converted',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='is_muslim',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='muslim_type',
            field=models.TextField(),
        ),
    ]
