# Generated by Django 4.1.7 on 2023-06-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_personaldata_is_converted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='is_converted',
            field=models.CharField(blank=True, choices=[('Birth', 'Since birth'), ('Convert', 'Converted')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='is_muslim',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='muslim_type',
            field=models.CharField(blank=True, choices=[('Sunni', 'Sunni'), ('Shia', 'Shia'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
