# Generated by Django 4.1.7 on 2023-06-17 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
