# Generated by Django 4.1.7 on 2023-06-17 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
