# Generated by Django 4.1.7 on 2023-06-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
